/**
 * main.js
 *
 * This files bundles several tasks from the tasks folder
 *
 */

'use strict';

var gulp = require('gulp'),
  helper = require('../helper');

var autogeneratedFolders = ['sc5-styleguide'];

//////////////////

//clean all but lib folder in www
gulp.task('project:clean', function (done) {
  helper.log('delete all autogenerated files and folders');
  return helper.clean([autogeneratedFolders], done);
});